apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: curvelift-com-tls
spec:
  secretName: curvelift-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: curvelift.com
  dnsNames:
    - curvelift.com
    - www.curvelift.com
